name: Deploy Docs

on:
    push:
        branches:
            - main
        paths:
            - 'apps/docs/**'
            - 'apps/h5-template/**'
            - 'packages/**'
            - 'package.json'
            - 'pnpm-lock.yaml'
            - '.github/workflows/deploy-docs.yml'
    workflow_dispatch:

permissions:
    contents: read
    pages: write
    id-token: write

concurrency:
    group: 'pages'
    cancel-in-progress: false

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0

            - name: Setup Node
              uses: actions/setup-node@v4
              with:
                  node-version: 20
                  registry-url: https://registry.npmjs.org/

            - name: Setup pnpm
              uses: pnpm/action-setup@v4
              with:
                  version: 8.15.6

            - name: Install dependencies
              run: pnpm install

            - name: Build h5-template with correct base path
              run: |
                  cd apps/h5-template
                  pnpm build:test
                  ls -la dist # 检查构建输出

            - name: Build docs
              run: |
                  cd apps/docs
                  pnpm run build

            - name: Copy h5-template dist to docs site-h5
              run: |
                  mkdir -p apps/docs/.vitepress/dist/site-h5
                  cp -r apps/h5-template/dist/* apps/docs/.vitepress/dist/site-h5/
                  # 确保资源文件权限正确
                  chmod -R 755 apps/docs/.vitepress/dist/site-h5

            - name: Show directory structure
              run: |
                  echo "=== Full directory structure of apps/docs/.vitepress/dist ==="
                  ls -laR apps/docs/.vitepress/dist
                  echo "=== Checking site-h5 directory ==="
                  ls -la apps/docs/.vitepress/dist/site-h5/
                  echo "=== Checking site-h5 subdirectories ==="
                  find apps/docs/.vitepress/dist/site-h5/ -type d -exec ls -la {} \;

            - name: Upload artifact
              uses: actions/upload-pages-artifact@v3
              with:
                  path: apps/docs/.vitepress/dist

    deploy:
        environment:
            name: github-pages
            url: ${{ steps.deployment.outputs.page_url }}
        runs-on: ubuntu-latest
        needs: build
        steps:
            - name: Deploy to GitHub Pages
              id: deployment
              uses: actions/deploy-pages@v4
